#!/bin/sh


# -------------------------------------------ToDo.API-----------------------------------------------------------------------------------------------

# Temporarily modify the project file to remove shift framework references. Linux
sed -i '/<ProjectReference Include="..\\..\\ShiftEntity\\ShiftEntity.Web\\ShiftEntity.Web.csproj" \\/d' ToDo.API/ToDo.API.csproj
sed -i '/<ProjectReference Include="..\\..\\ShiftEntity\\ShiftEntity.EFCore.SqlServer\\ShiftEntity.EFCore.SqlServer.csproj" \\/d' ToDo.API/ToDo.API.csproj
sed -i '/<ProjectReference Include="..\\..\\ShiftIdentity\\ShiftIdentity.Dashboard.AspNetCore\\ShiftIdentity.Dashboard.AspNetCore.csproj" \\/d' ToDo.API/ToDo.API.csproj

# Temporarily modify the project file to remove shift framework references. Windows
sed -i "/<ProjectReference Include=\"..\\\\..\\\\ShiftEntity\\\\ShiftEntity.Web\\\\ShiftEntity.Web.csproj\" \\/>/d" ToDo.API/ToDo.API.csproj
sed -i "/<ProjectReference Include=\"..\\\\..\\\\ShiftEntity\\\\ShiftEntity.EFCore.SqlServer\\\\ShiftEntity.EFCore.SqlServer.csproj\" \\/>/d" ToDo.API/ToDo.API.csproj
sed -i "/<ProjectReference Include=\"..\\\\..\\\\ShiftIdentity\\\\ShiftIdentity.Dashboard.AspNetCore\\\\ShiftIdentity.Dashboard.AspNetCore.csproj\" \\/>/d" ToDo.API/ToDo.API.csproj

# Stage the modified file
git add ToDo.API/ToDo.API.csproj

# ---------------------------------------------------------------------------------------------------------------------------------------------------------------------


# -------------------------------------------ToDo.Shared-----------------------------------------------------------------------------------------------

# Temporarily modify the project file to remove shift framework references. Linux
sed -i '/<ProjectReference Include="..\\..\\ShiftEntity\\ShiftEntity.Model\\ShiftEntity.Model.csproj" \\/d' ToDo.Shared/ToDo.Shared.csproj

# Temporarily modify the project file to remove shift framework references. Windows
sed -i "/<ProjectReference Include=\"..\\\\..\\\\ShiftEntity\\\\ShiftEntity.Model\\\\ShiftEntity.Model.csproj\" \\/>/d" ToDo.Shared/ToDo.Shared.csproj

# Stage the modified file
git add ToDo.Shared/ToDo.Shared.csproj

# ---------------------------------------------------------------------------------------------------------------------------------------------------------------------




# -------------------------------------------ToDo.Web-----------------------------------------------------------------------------------------------

# Temporarily modify the project file to remove shift framework references. Linux
sed -i '/<ProjectReference Include="..\\..\\ShiftBlazor\\ShiftBlazor\\ShiftBlazor.csproj" \\/d' ToDo.Web/ToDo.Web.csproj
sed -i '/<ProjectReference Include="..\\..\\ShiftIdentity\\ShiftIdentity.Blazor\\ShiftIdentity.Blazor.csproj" \\/d' ToDo.Web/ToDo.Web.csproj
sed -i '/<ProjectReference Include="..\\..\\ShiftIdentity\\ShiftIdentity.Dashboard.Blazor\\ShiftIdentity.Dashboard.Blazor.csproj" \\/d' ToDo.Web/ToDo.Web.csproj

# Temporarily modify the project file to remove shift framework references. Windows
sed -i "/<ProjectReference Include=\"..\\\\..\\\\ShiftBlazor\\\\ShiftBlazor\\\\ShiftBlazor.csproj\" \\/>/d" ToDo.Web/ToDo.Web.csproj
sed -i "/<ProjectReference Include=\"..\\\\..\\\\ShiftIdentity\\\\ShiftIdentity.Blazor\\\\ShiftIdentity.Blazor.csproj\" \\/>/d" ToDo.Web/ToDo.Web.csproj
sed -i "/<ProjectReference Include=\"..\\\\..\\\\ShiftIdentity\\\\ShiftIdentity.Dashboard.Blazor\\\\ShiftIdentity.Dashboard.Blazor.csproj\" \\/>/d" ToDo.Web/ToDo.Web.csproj

# Stage the modified file
git add ToDo.Web/ToDo.Web.csproj

# ---------------------------------------------------------------------------------------------------------------------------------------------------------------------